-- reset dữ liệu
-- [CN1]
UPDATE KHO_BAN SET SoLuongTon = 99 WHERE MaCN = 'CN001' AND MaSach = 'S0937';
COMMIT;
-- [CN2]
UPDATE KHO_BAN@gd1_to_gd2 SET SoLuongTon = 31 WHERE MaCN = 'CN002' AND MaSach = 'S0046';
COMMIT;



-- Read committed
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
UPDATE KHO_BAN SET SoLuongTon = 50 WHERE MaCN = 'CN001' AND MaSach = 'S0937';

UPDATE KHO_BAN@gd1_to_gd2 SET SoLuongTon = 5 WHERE MaCN = 'CN002' AND MaSach = 'S0046';

COMMIT;
SELECT SoLuongTon FROM KHO_BAN WHERE MaCN = 'CN001' AND MaSach = 'S0937';

--Serializable
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE KHO_BAN SET SoLuongTon = 50 WHERE MaCN = 'CN001' AND MaSach = 'S0937';

UPDATE KHO_BAN@gd1_to_gd2 SET SoLuongTon = 5 WHERE MaCN = 'CN002' AND MaSach = 'S0046';

COMMIT;
SELECT SoLuongTon FROM KHO_BAN WHERE MaCN = 'CN001' AND MaSach = 'S0937';

-- Kiểm tra kết quả
-- [CN1]
SELECT SoLuongTon FROM KHO_BAN
WHERE MaCN = 'CN001' AND MaSach = 'S0937';
-- [CN2]
SELECT SoLuongTon FROM KHO_BAN@gd1_to_gd2
WHERE MaCN = 'CN002' AND MaSach = 'S0046';
