--LOST UPDATE

--READ COMMITTED

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT SoLuongTon FROM GIAMDOC_CN1.KHO_BAN WHERE MaCN = 'CN001' AND MaSach = 'S0046'; 

UPDATE GIAMDOC_CN1.KHO_BAN SET SoLuongTon = 31 WHERE MaCN = 'CN001' AND MaSach = 'S0046';

COMMIT;

--SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SELECT SoLuongTon FROM GIAMDOC_CN1.KHO_BAN WHERE MaCN = 'CN001' AND MaSach = 'S0046'; 

UPDATE GIAMDOC_CN1.KHO_BAN SET SoLuongTon = 10 WHERE MaCN = 'CN001' AND MaSach = 'S0046';

COMMIT;
